package org.elasticflow.reader.message; 

/**
 * Process messages generated by middleware, such as kafka,rabitmq...
 * 
 * @author chengwen
 * @version 1.0
 * @date 2018-10-26 09:24
 */
public interface MessageHandler {
	public boolean handle(Object... args);
}
